name: Github Checkout

on: [push]

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2 # action을 만들때 남이 만든 action을 실행(Marketplace)
    - name: Run pwd 
      run: pwd
    - name: Run ls -al
      run: ls -al
